USE [master]
GO

/****** Object:  Database [Res]    Script Date: 11/09/2018 11:11:01 ص ******/
CREATE DATABASE [Res]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Res', FILENAME = N'I:\JustInMind_Projects\Resturant_Proto\DB_ResturantProto\Res.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Res_log', FILENAME = N'I:\JustInMind_Projects\Resturant_Proto\DB_ResturantProto\Res_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [Res] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Res].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Res] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Res] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Res] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Res] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Res] SET ARITHABORT OFF 
GO

ALTER DATABASE [Res] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Res] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [Res] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Res] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Res] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Res] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Res] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Res] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Res] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Res] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Res] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Res] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Res] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Res] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Res] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Res] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Res] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Res] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Res] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Res] SET  MULTI_USER 
GO

ALTER DATABASE [Res] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Res] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Res] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Res] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [Res] SET  READ_WRITE 
GO

